### ISSUE TITLE
"About us" Page leads nowhere and doesn't yet exist

### ISSUE THREAD

**Issue by DrM00G** [3D-Wizards-Inc/3D-Wizards-Inc#13]
Create the actual page for the navbar link to direct to. Add structure aka paragraphs for business introduction, business history, team member profiles (including headshots), and future plans.
For actual text feel free to use Lorum Ipsum text.

**Comment by hoopuiwa** [comment]
pushed johns changes he made, where he created the about us page and redirect, added some slight change and the lorum ipsum text
